/*
 *  Source machine generated by GadToolsBox V2.0
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : CCS
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_S_Edit                              0
#define GD_S_Reel                              1
#define GD_S_InTC                              2
#define GD_S_OutTC                             3
#define GD_S_DurTC                             4
#define GD_S_UseCnt                            5
#define GD_E_Edit                              6
#define GD_E_Reel                              7
#define GD_E_InTC                              8
#define GD_E_OutTC                             9
#define GD_E_DurTC                             10
#define GD_E_UseCnt                            11
#define GD_S_TextType                          12
#define GD_E_TextType                          13

#define GD_T_InTC                              14
#define GD_T_OutTC                             15
#define GD_T_DurTC                             16
#define GD_T_Type                              17
#define GD_T_GPI                               18

#define GD_O_TextType                          19

#define GD_TL_Edit                             20
#define GD_TL_TextType                         21

#define EditDisplay_CNT 22




extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern APTR                  VisualInfo;
extern struct Window        *EditDisplayWnd;
extern struct Gadget        *EditDisplayGList;
extern struct Gadget        *EditDisplayGadgets[EditDisplay_CNT];
extern UWORD                 EditDisplayLeft;
extern UWORD                 EditDisplayTop;
extern UWORD                 EditDisplayWidth;
extern UWORD                 EditDisplayHeight;
extern UBYTE                *EditDisplayWdt;
extern UBYTE                *S_TextType0Labels[];
extern UBYTE                *E_TextType0Labels[];
extern struct TextAttr       mflex10;
extern struct IntuiText      EditDisplayIText[];
extern UWORD                 EditDisplayGTypes[];
extern struct NewGadget      EditDisplayNGad[];
extern ULONG                 EditDisplayGTags[];
extern struct ColorSpec      ScreenColors[];
extern UWORD                 DriPens[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void EditDisplayRender( void );
extern int OpenEditDisplayWindow( void );
extern void CloseEditDisplayWindow( void );
