/*
 *  Source machine generated by GadToolsBox V2.0
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : CCS
 */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <clib/exec_protos.h>
#include <clib/intuition_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/utility_protos.h>
#include <string.h>

#include "EditDisplayGUI.h"

#include "editor.h"

struct Window         *EditDisplayWnd = NULL;
struct Gadget         *EditDisplayGList = NULL;
struct Gadget         *EditDisplayGadgets[EditDisplay_CNT];
UWORD                  EditDisplayLeft = 65;
UWORD                  EditDisplayTop = 131;
UWORD                  EditDisplayWidth = 500;
UWORD                  EditDisplayHeight = 220;
UBYTE                 *EditDisplayWdt = (UBYTE *)"Display Selector";

UBYTE *S_TextType0Labels[] = {
	(UBYTE *)"Descriptor",
	(UBYTE *)"Comments",
	(UBYTE *)"Notes",
	NULL };

UBYTE *E_TextType0Labels[] = {
	(UBYTE *)"Descriptor",
	(UBYTE *)"Comments",
	(UBYTE *)"Notes",
	NULL };

UBYTE *O_TextType0Labels[] = {
	(UBYTE *)"Combin. V/A (Default)",
	(UBYTE *)"Indiv.  V/A",
	(UBYTE *)"Combin. V, Indiv A.",
	NULL };

UBYTE *TL_TextType0Labels[] = {
	(UBYTE *)"Descriptor",
	(UBYTE *)"Comments",
	(UBYTE *)"Notes",
	(UBYTE *)"-None-",
	NULL };

struct IntuiText EditDisplayIText[] = {
	13, 0, JAM1,  28,  5, &mflex10, (UBYTE *)"ShotList Display", &EditDisplayIText[1],
	13, 0, JAM1, 252,  5, &mflex10, (UBYTE *)"EDL Display", &EditDisplayIText[2] ,
	13, 0, JAM1, 362,  5, &mflex10, (UBYTE *)"Transition Display", &EditDisplayIText[3] ,
	13, 0, JAM1, 28, 145, &mflex10, (UBYTE *)"Global Editor Settings", &EditDisplayIText[4] ,
	13, 0, JAM1, 360,145, &mflex10, (UBYTE *)"TimeLine Display", NULL
	 };

UWORD EditDisplayGTypes[] = {
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CYCLE_KIND,
	CYCLE_KIND,

	CHECKBOX_KIND,		// transition list
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,

	CYCLE_KIND,			// global stuff

	CHECKBOX_KIND,		// time lines settings
	CYCLE_KIND

};

struct NewGadget EditDisplayNGad[] = {
	112, 30, 26, 11, (UBYTE *)"Shot Number", NULL, GD_S_Edit, PLACETEXT_LEFT, NULL, NULL,
	112, 45, 26, 11, (UBYTE *)"Reel", NULL, GD_S_Reel, PLACETEXT_LEFT, NULL, NULL,
	112, 60, 26, 11, (UBYTE *)"In Time", NULL, GD_S_InTC, PLACETEXT_LEFT, NULL, NULL,
	112, 75, 26, 11, (UBYTE *)"Out Time", NULL, GD_S_OutTC, PLACETEXT_LEFT, NULL, NULL,
	112, 90, 26, 11, (UBYTE *)"Duration Time", NULL, GD_S_DurTC, PLACETEXT_LEFT, NULL, NULL,
	112, 105, 26,11, (UBYTE *)"Usage Count", NULL, GD_S_UseCnt, PLACETEXT_LEFT, NULL, NULL,

	304, 30, 26, 11, (UBYTE *)"EDL Number", NULL, GD_E_Edit, PLACETEXT_LEFT, NULL, NULL,
	304, 45, 26, 11, (UBYTE *)"Reel", NULL, GD_E_Reel, PLACETEXT_LEFT, NULL, NULL,
	304, 60, 26, 11, (UBYTE *)"In Time", NULL, GD_E_InTC, PLACETEXT_LEFT, NULL, NULL,
	304, 75, 26, 11, (UBYTE *)"Out Time", NULL, GD_E_OutTC, PLACETEXT_LEFT, NULL, NULL,
	304, 90, 26, 11, (UBYTE *)"Duration Time", NULL, GD_E_DurTC, PLACETEXT_LEFT, NULL, NULL,
	304, 105, 26,11, (UBYTE *)"Usage Count", NULL, GD_E_UseCnt, PLACETEXT_LEFT, NULL, NULL,

	032, 121, 112, 15, NULL, NULL, GD_S_TextType, 0, NULL, NULL,
	218, 121, 112, 15, NULL, NULL, GD_E_TextType, 0, NULL, NULL,

	460, 30, 26, 11, (UBYTE *)"In Time", NULL, GD_T_InTC, PLACETEXT_LEFT, NULL, NULL,
	460, 45, 26, 11, (UBYTE *)"Out Time", NULL, GD_T_OutTC, PLACETEXT_LEFT, NULL, NULL,
	460, 60, 26, 11, (UBYTE *)"Duration", NULL, GD_T_DurTC, PLACETEXT_LEFT, NULL, NULL,
	460, 75, 26, 11, (UBYTE *)"Type", NULL, GD_T_Type, PLACETEXT_LEFT, NULL, NULL,
	460, 90, 26, 11, (UBYTE *)"GPIB", NULL, GD_T_GPI, PLACETEXT_LEFT, NULL, NULL,

	026, 166, 195, 15, NULL, NULL, GD_O_TextType, 0, NULL, NULL,

	457, 166, 26, 11, (UBYTE *)"Edit Numbers", NULL, GD_TL_Edit, PLACETEXT_LEFT, NULL, NULL,
	371, 182, 112, 15, NULL, NULL, GD_TL_TextType, 0, NULL, NULL

};

ULONG EditDisplayGTags[] = {
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(GTCY_Labels), (ULONG)&S_TextType0Labels[ 0 ], (TAG_DONE),
	(GTCY_Labels), (ULONG)&E_TextType0Labels[ 0 ], (TAG_DONE),

	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),

	(GTCY_Labels), (ULONG)&O_TextType0Labels[ 0 ], (TAG_DONE),

	(TAG_DONE),
	(GTCY_Labels), (ULONG)&TL_TextType0Labels[ 0 ], (TAG_DONE)

};





void EditDisplayRender( void )
{
	UWORD		offx, offy;

	offx = EditDisplayWnd->BorderLeft;
	offy = EditDisplayWnd->BorderTop;

	Draw3DBox(  EditDisplayWnd->RPort, offx + 0, offy +  0, EditDisplayWidth-0, EditDisplayHeight, PEN_MBEV_SHINE, PEN_MBEV_BODY, PEN_MBEV_SHADOW );
	Draw3DLine( EditDisplayWnd->RPort, offx + 1, offy + 18, EditDisplayWidth-2, PEN_MBEV_SHADOW, PEN_MBEV_SHINE);

	Draw3DLine( EditDisplayWnd->RPort, offx + 1, offy + 140, EditDisplayWidth-2, PEN_MBEV_SHADOW, PEN_MBEV_SHINE);
	Draw3DLine( EditDisplayWnd->RPort, offx + 1, offy + 157, EditDisplayWidth-2, PEN_MBEV_SHADOW, PEN_MBEV_SHINE);

	Draw3DVLine( EditDisplayWnd->RPort, offx + 245, offy + 158, 59 , PEN_MBEV_SHADOW, PEN_MBEV_SHINE);

	PrintIText( EditDisplayWnd->RPort, EditDisplayIText, offx, offy );
}





int OpenEditDisplayWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		offx = Scr->WBorLeft, offy = Scr->WBorTop + Scr->RastPort.TxHeight + 1;

	if ( ! ( g = CreateContext( &EditDisplayGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < EditDisplay_CNT; lc++ ) {

		CopyMem((char * )&EditDisplayNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = &mflex10;
		ng.ng_LeftEdge  += offx;
		ng.ng_TopEdge   += offy;

		EditDisplayGadgets[ lc ] = g = CreateGadgetA((ULONG)EditDisplayGTypes[ lc ], g, &ng, ( struct TagItem * )&EditDisplayGTags[ tc ] );

		while( EditDisplayGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( EditDisplayWnd = OpenWindowTags( NULL,
				WA_Left,		EditDisplayLeft,
				WA_Top,			EditDisplayTop,
				WA_InnerWidth,	EditDisplayWidth,
				WA_InnerHeight,	EditDisplayHeight,
				WA_IDCMP,		CHECKBOXIDCMP|CYCLEIDCMP|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW|IDCMP_RAWKEY|IDCMP_VANILLAKEY|IDCMP_MENUPICK,
				WA_Flags,		WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Title,		EditDisplayWdt,
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	EditDisplayRender();

	AddGList(EditDisplayWnd, EditDisplayGadgets[0],NULL,NULL,NULL);
	RefreshGList(EditDisplayGadgets[0], EditDisplayWnd,NULL,NULL);

	return( 0L );
}

void CloseEditDisplayWindow( void )
{
	if ( EditDisplayWnd        ) {
		CloseWindow( EditDisplayWnd );
		EditDisplayWnd = NULL;
	}

	if ( EditDisplayGList      ) {
		FreeGadgets( EditDisplayGList );
		EditDisplayGList = NULL;
	}
}

